//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employees
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetailsTable
    {
        public int EID { get; set; }
        public string ENAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string LOCATION { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
    }
}
